name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        TEST_MODE: True
        WEBHOOK_SECRET: test_secret
        DEFAULT_EXCHANGE: bybit
        TEST_BALANCE_USDT: 100
      run: |
        python test_bot.py
        python test_webhook.py
        python test_exchange_selector.py
        python test_balance_scenario.py
    
    - name: Check code quality
      run: |
        pip install flake8
        flake8 bot/ --max-line-length=79 --ignore=E501,W503

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Security check
      run: |
        pip install bandit
        bandit -r bot/ -f json -o bandit-report.json || true
    
    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: bandit-report.json
